### ISSUE TITLE
When I delete a BelongsToMany relationship and then persist the entity then the deletion is not persisted.

### ISSUE THREAD

**Issue by Evertt** [analogueorm/analogue#71]
So I have a model `User` which BelongsToMany `Permission`. I've written a trait that does all the permission management, which looks like this:

```php
namespace App\Model\Traits;

use App\Model\Entities\Permission;
use App\Model\Repositories\PermissionRepository;

trait Permissions
{
    public function hasPermissionTo($action, $ownership = null, $entity = null)
    {
        $permission = $this->getStoredPermission($action, $ownership, $entity);

        return $this->permissions->contains($permission->id);
    }

    public function givePermissionTo($action, $ownership = null, $entity = null)
    {
        $permission = $this->getStoredPermission($action, $ownership, $entity);

        $this->attributes['permissions']->add($permission);

        return $this;
    }

    public function revokePermissionTo($action, $ownership = null, $entity = null)
    {
        $permission = $this->getStoredPermission($action, $ownership, $entity);

        $this->attributes['permissions']->remove($permission);

        return $this;
    }

    protected function getStoredPermission($action, $ownership, $entity)
    {
        if ($action instanceof Permission) return $action;

        if (is_object($entity)) $entity = get_class($entity);

        $repository = app(PermissionRepository::class);

        $ownership = [$ownership, 'any'];

        $conditions = compact('action', 'ownership', 'entity');

        $permission = $repository->firstMatching($conditions);

        if ($permission) return $permission;

        return new Permission($action, $ownership[0], $entity);
    }
}
```

And I use this trait in my `User` entity. Now take my word for it that the `getStoredPermission()` method works perfectly. Also, I've tested `givePermissionTo()` with this code:

```php
$user = $userRepository->find(1);
$user->givePermissionTo('edit', 'other', $user);
mapper($user)->store($user);
```

When I run that code, a permission is created and is also correctly linked to the user. So I was hoping that doing the following would delete the link:

```php
$user = $userRepository->find(1);
$user->revokePermissionTo('edit', 'other', $user);
mapper($user)->store($user);
```

Now I can see that the code **does** correctly remove the permission from the EntityCollection in `$user->attributes['permissions']`, but somehow when I store the user, it doesn't remove the link in the database.

**Comment by RemiCollin** [comment]
I recently corrected a bug where this could happens when several find() method were fired on the same entity. Can you please switch to system-refactoring branch and tell me if you still got this bug ?

**Comment by RemiCollin** [comment]
Refactoring is finished and I merged into 5.1 branch. Can you  tell me if it fixes this ?

**Comment by Evertt** [comment]
I will, in a few hours probably, first I have some other stuff to finish. :-)

**Comment by Evertt** [comment]
Now this does work better, but still not fully as it should and that has to do with EntityCollection.

You see when I add stuff to EntityCollection it gets an arbitrary array key in the array `$this->items`, for example I'd have:

![screen shot 2015-10-04 at 13 05 22](https://cloud.githubusercontent.com/assets/1267282/10267543/bfb5a19a-6a98-11e5-901d-7f445ea51659.png)

Or

![screen shot 2015-10-04 at 13 02 29](https://cloud.githubusercontent.com/assets/1267282/10267546/c9284e6c-6a98-11e5-992e-2a775ccea7e9.png)

However when I try to remove stuff from the EntityCollection with `$this->attributes['permissions']->remove($permission)` it expects the array key of the item to correspond the model key (i.e. the id column). So removing stuff from the EntityCollection still doesn't work as expected.

**Comment by RemiCollin** [comment]
Ok i'll have a look.

**Comment by smallhadroncollider** [comment]
I'm also coming across the same issue.

I have a `Cues` model which has many `Instrumentation`s. When I updated the `Cue` and remove an `Instrumentation` it adds any new ones, but any old ones that are no longer on the `Cue` do not get removed from the database.
